
package uy.com.antel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceServlet", targetNamespace = "http://antel.com.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceServlet {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eco", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.Eco")
    @ResponseWrapper(localName = "ecoResponse", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.EcoResponse")
    public String eco(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
