
package uy.com.antel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceServlet", targetNamespace = "http://antel.com.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceServlet {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns uy.com.antel.ResultadoOperacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "anularTicket", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.AnularTicket")
    @ResponseWrapper(localName = "anularTicketResponse", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.AnularTicketResponse")
    public ResultadoOperacionPosta anularTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eco", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.Eco")
    @ResponseWrapper(localName = "ecoResponse", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.EcoResponse")
    public String eco(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns uy.com.antel.ResultadoOperacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "venderTicket", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.VenderTicket")
    @ResponseWrapper(localName = "venderTicketResponse", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.VenderTicketResponse")
    public ResultadoOperacionPosta venderTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        Ticket arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
